config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    resources :likes
  end

  resources :users do
    get 'friend_requests', to: 'users#showrequests' 
    member do
      get :create_friendship
      get :update_friendship
      get :destroy_friendship
    end
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', edit: 'edit-user'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get 'users/show/:id', to: 'users#show'
  get 'users', to: 'users#index'
  
  authenticated :user do
    root to: 'posts#index'
  end
  
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates_presence_of :content

  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(content: comment_params[:content], user: current_user)
    if @comment.save
      flash[:success] = 'Comment created successfully!'
    else
      flash[:danger] = 'Comment creation failed'
    end
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'Comment deleted successfully!'
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  # def post_by_?(user)
end

app/views/comments/_comment.html.erb
<div class="card">
  <p>Commented by - <strong><%= comment.user.name %></strong></p>
  <p><%= comment.content %></p>
  <% if comment.user == current_user %>
    <%= link_to 'Delete comment', post_comment_path(@post.id, id: comment.id), method: :delete %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, Comment.new]) do |f| %>
  <div class="field">
    <%= f.label :content, 'Please write your comment' %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.submit 'Submit' %>
  </div>
<% end %>