config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    resources :likes
  end

  resources :users do
    get 'friend_requests', to: 'users#showrequests' 
    member do
      get :create_friendship
      get :update_friendship
      get :destroy_friendship
    end
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', edit: 'edit-user'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get 'users/show/:id', to: 'users#show'
  get 'users', to: 'users#index'
  
  authenticated :user do
    root to: 'posts#index'
  end
  
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
  
  validates_presence_of :name

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :friends, through: :friendships

  def self.all_except(user)
    where.not(id: user)
  end
  
  # Facebook login
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all_except(current_user)
  end

  def show
    @user = current_user
    @posts = @user.posts
  end

  def showrequests
    @requested_friends = User.joins('INNER JOIN friendships ON users.id=friendships.friend_id
                                    AND friendships.status=1').where.not('users.id=?', current_user.id).distinct
  end

  def create_friendship
    @user = User.find(params[:id])
    current_user.friendships.create!(friend_id: @user.id, status: 0)
    flash[:success] = 'Friend request sent'
    redirect_to users_path
  end

  def update_friendship
    @user = User.find(params[:id])
    Friendship.find_by(user: current_user, friend: @user).accepted!
    flash[:success] = 'Friend added'
    redirect_to users_path
  end

  def destroy_friendship
    @user = User.find(params[:id])
    Friendship.find_by(user: current_user, friend: @user).destroy
    flash[:success] = 'Friend request deleted'
    redirect_to users_path
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_user.html.erb
<h4><%= user.name %></h4>
<p><%= user.email %></p>
<% if !Friendship.exists?(user: current_user, friend: user)%>
  <%= link_to 'Add friend',create_friendship_user_path(user.id) %>
<% else %>
	<% if Friendship.find_by(user:current_user,friend: user).pending? %>
		<%= link_to 'Cancel Friend Request',destroy_friendship_user_path(user.id) %>
	<% end %>
		<% if Friendship.find_by(user:current_user,friend: user).requested? %>
		<%= link_to 'Accept Friend Request',update_friendship_user_path(user.id) %>
	<% end %>
<% end %>
<br>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
  <%= render user %>
<% end %>

app/views/users/show.html.erb
<h2>Profile</h2>

<%= gravatar_image_tag(@user.email.gsub('spam', 'mdeering'), alt: @user.name ) %>
<p>Name - <strong><%= @user.name %></strong></p>
<p>Email - <strong><%= @user.email %></strong></p>

<h2>My Posts</h2>
<%= render @posts %>

app/views/users/showrequests.html.erb
<%= render @requested_friends%>