config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    resources :likes
  end

  resources :users do
    get 'friend_requests', to: 'users#showrequests' 
    member do
      get :create_friendship
      get :update_friendship
      get :destroy_friendship
    end
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', edit: 'edit-user'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get 'users/show/:id', to: 'users#show'
  get 'users', to: 'users#index'
  
  authenticated :user do
    root to: 'posts#index'
  end
  
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  default_scope { order(created_at: :desc) }
  validates_presence_of :content

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: %i[edit update destroy show]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @posts = current_user.posts + Post.joins("INNER JOIN friendships ON posts.user_id=friendships.user_id
                                             AND friendships.friend_id=#{current_user.id}")
    @posts = @posts.sort { |a, b| b.created_at <=> a.created_at }
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
      flash[:success] = 'Post created successfully'
    else
      flash.now[:danger] = 'Post creation failed. Please enter valid information'
      render 'new'
    end
  end

  def edit; end

  def show; end

  def update
    if @post.update(post_params)
      flash[:success] = 'Post saved successfully'
      redirect_to root_path
    else
      flash.now[:danger] = 'Post update failed. Please enter valid information'
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted successfully'
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:content, :image_link)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def correct_user
    return if current_user == @post.user

    flash[:danger] = "You're not authorized to visit this page."
    redirect_to root_path
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def post_exists?(post)
    post.image_link != '' && !post.image_link.nil?
  end

  def current_post?(post)
    post.user == current_user
  end
end

app/views/posts/_post.html.erb
<div class="card">
  <p><%= link_to post.content, post %></p>
  <% if post_exists?(post) %>
    <img src="<%= post.image_link %>" alt="<%= post.content %>">
  <% end %>
  <p><%= post.user.name %></p>
  <div>
    <span><%= pluralize(post.comments.count, 'comment') %></span>
    <span><%= pluralize(post.likes.count , 'like') %></span>
  </div>
  <div>
    <span><%= link_to  'Comment', post %></span>
    <% if liked?(post) %>
      <span><%= link_to 'Unlike', post_like_path(post.id, id: current_like(post).id), method: :delete %></span>
    <% else %>
      <span><%= link_to 'Like', post_likes_path(post), method: :post %></span>
    <% end %>
  </div>
  
  <div>
    <% if current_post?(post) %>
      <span><%= link_to "Edit post", edit_post_path(post), class: 'btn btn-primary' %></span>
      <span><%= link_to "Delete post", post, method: :delete, class: 'btn btn-primary' %></span>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for(@post) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :image_link %>
  <%= f.text_field :image_link %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= form_for(@post) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :image_link %>
  <%= f.text_field :image_link %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/show.html.erb
<div class="card">
  <h3><%= @post.content %></h3>
  <% if post_exists?(@post) %>
    <img src="<%= @post.image_link %>" alt="<%= @post.content %>">
  <% end %>
  <p><%= @post.user.name %></p>
  <div>
    <span><%= pluralize(@post.comments.count, 'comment') %></span>
    <span><%= pluralize(@post.likes.count , 'like') %></span>
  </div>
  <% if liked?(@post) %>
    <%= link_to 'Unlike', post_like_path(@post.id, id: current_like(@post).id), method: :delete %>
  <% else %>
    <%= link_to 'Like', post_likes_path(@post), method: :post %>
  <% end %>  
  <% if current_post?(@post) %>
    <div>
      <span><%= link_to "Edit post", edit_post_path(@post), class: 'btn btn-primary' %></span>
      <span><%= link_to "Delete post", @post, method: :delete, class: 'btn btn-primary' %></span>
    </div>
  <% end %>
  
  <%= render 'comments/form' %>
  <%= render @post.comments %>
  
  
</div>