config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    resources :likes
  end

  resources :users do
    get 'friend_requests', to: 'users#showrequests' 
    member do
      get :create_friendship
      get :update_friendship
      get :destroy_friendship
    end
  end

  devise_for :users, path: '', path_names: { sign_up: 'signup', sign_in: 'login', edit: 'edit-user'},
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get 'users/show/:id', to: 'users#show'
  get 'users', to: 'users#index'
  
  authenticated :user do
    root to: 'posts#index'
  end
  
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Facebook", root_path, class: "navbar-brand" %> 
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if current_user.nil? %>
           <%= link_to 'Log In', new_user_session_path, class: 'nav-item nav-link' %>
           <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-item nav-link' %>
           <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: 'nav-item nav-link' %>
          <% else %>
            <%= link_to 'Users', users_path, class: 'nav-item nav-link' %>
            <%= link_to "#{current_user.name.split.first}'s Feed", root_path, class: 'nav-item nav-link' %>
            <%= link_to 'Friend Requests', user_friend_requests_path(current_user), class: 'nav-item nav-link' %>
            <%= link_to 'Create post', new_post_path, class: 'nav-item nav-link' %>
            <%= link_to 'View Profile', user_path(current_user), class: 'nav-item nav-link' %>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
          <% end %>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    
      <%= yield %>
    </div>
  </body>
</html>